name: CI Pipeline

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Run PHP_CodeSniffer
        run: vendor/bin/phpcs --standard=PSR12 src/

  phpunit:
    runs-on: ubuntu-latest
    env:
      DB_HOST: 127.0.0.1
      DB_NAME: test_db
      DB_USER: root
      DB_PASSWORD: password

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Wait for MySQL to be ready
        run: sleep 10

      - name: Run PHPUnit tests
        run: vendor/bin/phpunit --testdox
