name: PHP Code Beautifier and Fixer

on:
  workflow_dispatch:
    branches: [ master ]

jobs:
  phpcbf:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2.12'  # Adjust as needed
          tools: composer

      - name: Install dependencies
        run: composer install

      - name: Run PHP Code Beautifier and Fixer
        run: vendor/bin/phpcbf --standard=PSR12 src/

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Apply code style fixes via PHP Code Beautifier and Fixer"
        continue-on-error: true  # Ignore error if no changes to commit

      - name: Push changes
        run: git push
        if: success()
